DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS restaurants;

CREATE TABLE restaurants (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  restaurantName VARCHAR (50) NOT NULL,
  username VARCHAR (50) NOT NULL,
  description VARCHAR (500) NOT NULL,
  createdAt VARCHAR (50) NOT NULL,
  photoUrls VARCHAR (500)
);

\COPY restaurants FROM 'data_seedtest.tsv' DELIMITER E'\t';

SELECT setval(pg_get_serial_sequence('restaurants', 'id'), MAX(id)) FROM restaurants;

CREATE TABLE photos (
  id INTEGER,
  restaurant_id INTEGER,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
);

\COPY photos FROM 'data_test_photos.tsv' DELIMITER E'\t';
